"""initial schema

Revision ID: 746b748867f2
Revises: 
Create Date: 2026-09-13 16:59:40.565142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '746b748867f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=False),
    sa.Column('desk_number', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directory_redirect_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('body_part', sa.Text(), nullable=True),
    sa.Column('contact', sa.Text(), nullable=False),
    sa.CheckConstraint('category IS NOT NULL OR body_part IS NOT NULL', name='ck_redirect_rule_has_match_field'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('degree', sa.Text(), nullable=True),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('npi', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('home_zip', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('ix_patients_last_name_lower_dob', [sa.literal_column('lower(last_name)'), 'date_of_birth'], unique=False)

    op.create_table('practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('suite', sa.Text(), nullable=True),
    sa.Column('zip', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('main_phone', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', name='uq_practice_name_address')
    )
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('body_part', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('urgency', sa.Text(), nullable=True),
    sa.Column('patient_phrasing', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('default_appointment_type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('zip_centroids',
    sa.Column('zip', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=False),
    sa.Column('longitude', sa.Numeric(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('zip')
    )
    op.create_table('appointment_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open', 'held', 'booked')", name='ck_appointment_slot_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_slots', schema=None) as batch_op:
        batch_op.create_index('ix_appointment_slots_doctor_status_start', ['doctor_id', 'status', 'start_time'], unique=False)
        batch_op.create_index('uq_appointment_slots_doctor_start_booked', ['doctor_id', 'start_time'], unique=True, postgresql_where=sa.text("status = 'booked'"))

    op.create_table('doctor_practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'practice_id', name='uq_doctor_practice')
    )
    op.create_table('term_eligibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'doctor_id', name='uq_term_eligibility_term_doctor')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('appointment_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'cancelled')", name='ck_appointment_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slots.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vogent_call_id', sa.Text(), nullable=False),
    sa.Column('caller_phone', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_term_id', sa.Integer(), nullable=True),
    sa.Column('raw_complaint', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'scheduled', 'no_match', 'no_slots', 'abandoned', 'failed')", name='ck_call_status'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['matched_term_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vogent_call_id')
    )
    # appointments.call_id / calls.appointment_id is a genuine FK cycle --
    # calls must exist before this constraint can be added, so it's applied
    # as a separate statement rather than inline on appointments' create_table.
    op.create_foreign_key(
        'fk_appointments_call_id', 'appointments', 'calls', ['call_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_appointments_call_id', 'appointments', type_='foreignkey')
    op.drop_table('calls')
    op.drop_table('appointments')
    op.drop_table('term_eligibility')
    op.drop_table('doctor_practices')
    with op.batch_alter_table('appointment_slots', schema=None) as batch_op:
        batch_op.drop_index('uq_appointment_slots_doctor_start_booked', postgresql_where=sa.text("status = 'booked'"))
        batch_op.drop_index('ix_appointment_slots_doctor_status_start')

    op.drop_table('appointment_slots')
    op.drop_table('zip_centroids')
    op.drop_table('users')
    op.drop_table('terms')
    op.drop_table('practices')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('ix_patients_last_name_lower_dob')

    op.drop_table('patients')
    op.drop_table('doctors')
    op.drop_table('directory_redirect_rules')
    op.drop_table('directory_entries')
    # ### end Alembic commands ###
