"""add imaging and patient prerequisites

Revision ID: 7a600a9a551e
Revises: 746b748867f2
Create Date: 2026-09-20 13:27:04.909293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a600a9a551e'
down_revision = '746b748867f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imaging_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('open', 'held', 'booked')", name='ck_imaging_slot_status'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imaging_slots', schema=None) as batch_op:
        batch_op.create_index('ix_imaging_slots_practice_modality_status_start', ['practice_id', 'modality', 'status', 'start_time'], unique=False)
        batch_op.create_index('uq_imaging_slots_practice_modality_start_booked', ['practice_id', 'modality', 'start_time'], unique=True, postgresql_where=sa.text("status = 'booked'"))

    op.create_table('patient_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('satisfied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'term_id', 'requirement', name='uq_patient_prerequisite')
    )
    # call_id's FK to calls.id is added separately below via
    # op.create_foreign_key(), NOT declared inline here. Alembic does not
    # actually defer an inline use_alter=True FK inside create_table() the
    # way SQLAlchemy's create_all() does -- it silently omits it. This bit
    # appointments.call_id in the initial migration and was caught there by
    # a skeptic review; verified again here (via psql \d + pg_constraint)
    # that the inline form really does produce a table with no such
    # constraint at all before switching to this form.
    op.create_table('imaging_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'cancelled')", name='ck_imaging_appointment_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['imaging_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    op.create_foreign_key(
        'fk_imaging_appointments_call_id', 'imaging_appointments', 'calls', ['call_id'], ['id']
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imaging_appointment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_calls_imaging_appointment_id', 'imaging_appointments', ['imaging_appointment_id'], ['id']
        )

    with op.batch_alter_table('practices', schema=None) as batch_op:
        # server_default backfills existing rows -- the model's Python-side
        # default=False only applies to new rows, not this ALTER TABLE.
        batch_op.add_column(sa.Column('has_mri', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.drop_column('has_mri')

    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_constraint('fk_calls_imaging_appointment_id', type_='foreignkey')
        batch_op.drop_column('imaging_appointment_id')

    op.drop_table('imaging_appointments')
    op.drop_table('patient_prerequisites')
    with op.batch_alter_table('imaging_slots', schema=None) as batch_op:
        batch_op.drop_index('uq_imaging_slots_practice_modality_start_booked', postgresql_where=sa.text("status = 'booked'"))
        batch_op.drop_index('ix_imaging_slots_practice_modality_status_start')

    op.drop_table('imaging_slots')
    # ### end Alembic commands ###
