"""add insurance carrier and referral rule tables

Revision ID: ef8ddf194f24
Revises: 7645902601a2
Create Date: 2026-10-04 22:16:27.804894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8ddf194f24'
down_revision = '7645902601a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('insurance_referral_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('plan_tier', sa.Text(), nullable=True),
    sa.Column('requires_referral', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['insurance_carriers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier_id', 'plan_tier', name='uq_insurance_referral_rule')
    )
    with op.batch_alter_table('insurance_referral_rules', schema=None) as batch_op:
        batch_op.create_index('uq_insurance_referral_rules_carrier_wide', ['carrier_id'], unique=True, postgresql_where=sa.text('plan_tier IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_referral_rules', schema=None) as batch_op:
        batch_op.drop_index('uq_insurance_referral_rules_carrier_wide', postgresql_where=sa.text('plan_tier IS NULL'))

    op.drop_table('insurance_referral_rules')
    op.drop_table('insurance_carriers')
    # ### end Alembic commands ###
